"""add scenarios

Revision ID: 8489d31cb420
Revises: a2aa08c0b304
Create Date: 2020-05-28 14:09:48.533186

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '8489d31cb420'
down_revision = 'a2aa08c0b304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenarios',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('scenario_name', sa.String(), nullable=False),
                    sa.Column('bot_under_test', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('scenario_name', 'bot_under_test', name='_name_bot_uc')
                    )
    op.create_table('scenario_conversation',
                    sa.Column('scenarios_id', sa.Integer(), nullable=True),
                    sa.Column('conversation_id', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.conversation_id'], ),
                    sa.ForeignKeyConstraint(['scenarios_id'], ['scenarios.id'], )
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scenario_conversation')
    op.drop_table('scenarios')
    # ### end Alembic commands ###
