"""Initial migration.

Revision ID: a2aa08c0b304
Revises: 
Create Date: 2020-05-22 17:19:05.647286

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a2aa08c0b304'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
                    sa.Column('conversation_id', sa.String(length=255), nullable=False),
                    sa.Column('bot_id', sa.String(length=255), nullable=False),
                    sa.Column('token', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('conversation_id')
                    )
    op.create_table('performance_testing',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('bot_under_test', sa.String(length=255), nullable=False),
                    sa.Column('start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('end', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('performance_record',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('performance_testing_id', sa.Integer(), nullable=False),
                    sa.Column('message', sa.String(length=255), nullable=False),
                    sa.Column('received_valid', sa.Boolean(), nullable=False),
                    sa.Column('response_time', sa.Float(), ),
                    sa.ForeignKeyConstraint(['performance_testing_id'], ['performance_testing.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('performance_record')
    op.drop_table('performance_testing')
    op.drop_table('conversations')
    # ### end Alembic commands ###
